// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow.Shared.Entities;

#nullable disable

namespace TaskFlow.Shared.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20260407092555_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow.Share.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            CreatedDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Write comprehensive documentation for all API endpoints including request/response examples",
                            DueDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 0,
                            Title = "Complete API Documentation"
                        },
                        new
                        {
                            Id = new Guid("a0000002-0000-0000-0000-000000000002"),
                            CreatedDate = new DateTime(2025, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Resolve the JWT token expiration issue in the login endpoint",
                            DueDate = new DateTime(2025, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Status = 0,
                            Title = "Fix Authentication Bug"
                        },
                        new
                        {
                            Id = new Guid("a0000003-0000-0000-0000-000000000003"),
                            CreatedDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Add unit tests for the TaskService class with 90% code coverage",
                            DueDate = new DateTime(2025, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 0,
                            Title = "Implement Unit Tests"
                        },
                        new
                        {
                            Id = new Guid("a0000004-0000-0000-0000-000000000004"),
                            CreatedDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Update all outdated NuGet packages to latest stable versions",
                            DueDate = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 0,
                            Status = 0,
                            Title = "Update NuGet Packages"
                        },
                        new
                        {
                            Id = new Guid("a0000005-0000-0000-0000-000000000005"),
                            CreatedDate = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Review and optimize slow-performing database queries",
                            DueDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 2,
                            Title = "Optimize Database Queries"
                        },
                        new
                        {
                            Id = new Guid("a0000006-0000-0000-0000-000000000006"),
                            CreatedDate = new DateTime(2025, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create reusable UI components for the task management dashboard",
                            DueDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 0,
                            Title = "Design New UI Components"
                        },
                        new
                        {
                            Id = new Guid("a0000007-0000-0000-0000-000000000007"),
                            CreatedDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Review pull requests from team members and provide feedback",
                            DueDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 0,
                            Title = "Code Review Session"
                        },
                        new
                        {
                            Id = new Guid("a0000008-0000-0000-0000-000000000008"),
                            CreatedDate = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Deploy latest version to production environment with zero downtime",
                            DueDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 0,
                            Title = "Deploy to Production"
                        },
                        new
                        {
                            Id = new Guid("a0000009-0000-0000-0000-000000000009"),
                            CreatedDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Document all changes and features for the upcoming v2.0 release",
                            DueDate = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 0,
                            Status = 0,
                            Title = "Write Release Notes"
                        },
                        new
                        {
                            Id = new Guid("a0000010-0000-0000-0000-000000000010"),
                            CreatedDate = new DateTime(2025, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Perform security audit and vulnerability assessment",
                            DueDate = new DateTime(2025, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Status = 2,
                            Title = "Security Audit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
